name: dart_mwebd
description: An example of how to use the c-shared library of mwebd-wrapper with dart
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
    ffi: ^2.1.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
