name: Build iOS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build iOS Static Library
    runs-on: macOS-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.3'

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Static C Archive
        run: |
          ./build_ios.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mwebd-ios-library
          path: ios_lib/
          if-no-files-found: error
